#!/usr/bin/env node

/* ------------------------------------------------
  *
  * export WINEARCH=win64
  * yarn add electron-winstaller
  *
  *
------------------------------------------------ */
const cwd = process.cwd();
const path = require('path');
const { createWindowsInstaller } = require('electron-winstaller');

function getInstallerConfig () {
  console.log('Creating windows installer');
  const rootpath = path.join('./')
  const outputpath = path.join(rootpath, 'release-builds')

  return Promise.resolve();
}

getInstallerConfig()
  .then(createWindowsInstaller)
  .catch((error) => {
    console.error(error.message || error)
    process.exit(1)
  });
