#!/usr/bin/env node

// ------------------------------------------------
// INSTALL:
// - brew cask install xquartz
// - brew install wine
// - `export WINEARCH=win64`
// ------------------------------------------------ */

const cwd = process.cwd();
const path = require('path');
const packager = require('electron-packager');

packager({
  // available options
  // https://github.com/electron-userland/electron-packager/blob/master/docs/api.md
  platform: 'win32',
  dir: path.join(cwd),
  packageManager: 'yarn',
  out: path.join(cwd, 'releases')
})
.then((apppaths) => {
  console.log('Application packaged with success');
});

/*
const cwd = process.cwd();
const path = require('path');
const { createWindowsInstaller } = require('electron-winstaller');

function getInstallerConfig () {
  console.log('Creating windows installer');
  const rootpath = path.join('./')
  const outputpath = path.join(rootpath, 'release-builds')

  return Promise.resolve();
}

getInstallerConfig()
  .then(createWindowsInstaller)
  .catch((error) => {
    console.error(error.message || error)
    process.exit(1)
  });
*/
