#!/usr/bin/env node

/* ------------------------------------------------
  *
  *
  * yarn add electron-winstaller
  *
  *
------------------------------------------------ */
const path = require('path');
const { createWindowsInstaller } = require('electron-winstaller');

function getInstallerConfig () {
  console.log('creating windows installer')
  const inputpath = path.join('./')
  const outputpath = path.join(inputpath, 'release-builds')

  return Promise.resolve({
    noMsi: true,
    authors: 'IZIGES',
    appDirectory: path.join(outputpath, 'Electron-tutorial-app-win32-ia32/'),
    exe: 'electron-tutorial-app.exe',
    setupExe: 'ElectronTutorialAppInstaller.exe',
    outputDirectory: path.join(outputpath, 'windows-installer'),
    // setupIcon: path.join(inputpath, 'assets', 'icons', 'win', 'icon.ico')
  });
}

getInstallerConfig()
  .then(createWindowsInstaller)
  .catch((error) => {
    console.error(error.message || error)
    process.exit(1)
  });
